### ISSUE TITLE
Not Working on Size Classes

### ISSUE THREAD

**Issue by qasimmehboob** [StuartMorris0/SPMZoomableUIImageView#1]
When i enable size classes it is not working? you have any idea why how can i fix this problem?

**Comment by StuartMorris0** [comment]
Hey @qasimmehboob. Can you provide a little more information, or a link to a test project with this enabled and showing the issue please?

**Comment by qasimmehboob** [comment]
@StuartMorris0 : For testing you just enable "Use Size Classes" in Demo Project you Uploaded here. The problem is when i enable size classes then after view controller appear the image is not center and fit to device screen. The image is like floating on screen.

**Comment by StuartMorris0** [comment]
Thanks, its going to be a while before I can look into this. But in the meantime if you find a fix, feel free to submit a pull request. Thanks

**Comment by hemangshah** [comment]
@StuartMorris0 – Any updates?

**Comment by StuartMorris0** [comment]
I've added a fix in latest push: https://github.com/StuartMorris0/SPMZoomableUIImageView/commit/602e5b851f1502f957bbb5838fd138a25c5998a1

> Added Size Class Support
> - Added a launch screen to resolve full screen not working
> - Removed the constraints at build time (from IB), as they are re-created in the view controller.
> - Tested and zoom/double tap working as expected

If you are looking for a swift alternative please check out our tutorial website here:
https://apptillery.info/development/zoomable-uiscrollview/

If you have any improvements, feel free to submit a pull request.
